In [1]:
import pandas as pd
import numpy as np
from numpy import*

In [2]:

matrix2 = matrix('3,2,4,2,4,5,4;5,5,9,2,6,1,4;3,4,1,5,4,3,2;7,5,2,1,4,2,1;4,5,4,5,7,5,4;2,3,4,0,3,5,7;6,5,2,0,2,3,5;3,2,4,0,6,2,4;5,2,5,2,6,1,4;3,4,1,4,1,3,2')

In [3]:
matrix2

matrix([[3, 2, 4, 2, 4, 5, 4],
        [5, 5, 9, 2, 6, 1, 4],
        [3, 4, 1, 5, 4, 3, 2],
        [7, 5, 2, 1, 4, 2, 1],
        [4, 5, 4, 5, 7, 5, 4],
        [2, 3, 4, 0, 3, 5, 7],
        [6, 5, 2, 0, 2, 3, 5],
        [3, 2, 4, 0, 6, 2, 4],
        [5, 2, 5, 2, 6, 1, 4],
        [3, 4, 1, 4, 1, 3, 2]])

In [4]:
matrix2 = pd.DataFrame(matrix2)

In [5]:
matrix2

0  1  2  3  4  5  6
0  3  2  4  2  4  5  4
1  5  5  9  2  6  1  4
2  3  4  1  5  4  3  2
3  7  5  2  1  4  2  1
4  4  5  4  5  7  5  4
5  2  3  4  0  3  5  7
6  6  5  2  0  2  3  5
7  3  2  4  0  6  2  4
8  5  2  5  2  6  1  4
9  3  4  1  4  1  3  2

In [6]:
corr_matrix = matrix2.corr().abs()

In [7]:
corr_matrix

0         1         2         3         4         5         6
0  1.000000  0.536422  0.070644  0.215774  0.096620  0.534629  0.355862
1  0.536422  1.000000  0.077232  0.265775  0.132304  0.053134  0.287819
2  0.070644  0.077232  1.000000  0.205055  0.631988  0.300312  0.408062
3  0.215774  0.265775  0.205055  1.000000  0.136241  0.180445  0.487062
4  0.096620  0.132304  0.631988  0.136241  1.000000  0.219060  0.063688
5  0.534629  0.053134  0.300312  0.180445  0.219060  1.000000  0.375587
6  0.355862  0.287819  0.408062  0.487062  0.063688  0.375587  1.000000

In [8]:
cov_matrix_invs = np.linalg.inv(np.cov(matrix2,rowvar=0))

In [9]:
cov_matrix_invs= np.asmatrix(cov_matrix_invs)

In [10]:
cov_matrix_invs

matrix([[ 1.38538175, -1.00414639,  0.12345937,  0.62342676, -0.34143257,
          0.36103491,  0.41628122],
        [-1.00414639,  1.39599969, -0.20864223, -0.55142139,  0.40017727,
         -0.28667562, -0.1416828 ],
        [ 0.12345937, -0.20864223,  0.55166174,  0.01863924, -0.36687401,
          0.37200851, -0.40990443],
        [ 0.62342676, -0.55142139,  0.01863924,  0.78734436, -0.28711461,
         -0.17864354,  0.59853784],
        [-0.34143257,  0.40017727, -0.36687401, -0.28711461,  0.62999044,
         -0.10289127,  0.01259666],
        [ 0.36103491, -0.28667562,  0.37200851, -0.17864354, -0.10289127,
          1.02021169, -0.60032874],
        [ 0.41628122, -0.1416828 , -0.40990443,  0.59853784,  0.01259666,
         -0.60032874,  1.22719674]])

In [11]:
mean_of_matrix2 = np.mean(matrix2, axis=0)

In [12]:
mean_of_matrix2

0    4.1
1    3.7
2    3.6
3    2.1
4    4.3
5    3.0
6    3.7
dtype: float64

In [13]:
#(X-µ)
x_sub_mean_all = np.subtract(matrix2, mean_of_matrix2)

In [14]:
x_sub_mean_all

0    1    2    3    4    5    6
0 -1.1 -1.7  0.4 -0.1 -0.3  2.0  0.3
1  0.9  1.3  5.4 -0.1  1.7 -2.0  0.3
2 -1.1  0.3 -2.6  2.9 -0.3  0.0 -1.7
3  2.9  1.3 -1.6 -1.1 -0.3 -1.0 -2.7
4 -0.1  1.3  0.4  2.9  2.7  2.0  0.3
5 -2.1 -0.7  0.4 -2.1 -1.3  2.0  3.3
6  1.9  1.3 -1.6 -2.1 -2.3  0.0  1.3
7 -1.1 -1.7  0.4 -2.1  1.7 -1.0  0.3
8  0.9 -1.7  1.4 -0.1  1.7 -2.0  0.3
9 -1.1  0.3 -2.6  1.9 -3.3  0.0 -1.7

In [15]:
matrix2.index.values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [16]:
x_sub_mean_all = pd.DataFrame(x_sub_mean_all,index=matrix2.index.values)

In [17]:
x_sub_mean_all

0    1    2    3    4    5    6
0 -1.1 -1.7  0.4 -0.1 -0.3  2.0  0.3
1  0.9  1.3  5.4 -0.1  1.7 -2.0  0.3
2 -1.1  0.3 -2.6  2.9 -0.3  0.0 -1.7
3  2.9  1.3 -1.6 -1.1 -0.3 -1.0 -2.7
4 -0.1  1.3  0.4  2.9  2.7  2.0  0.3
5 -2.1 -0.7  0.4 -2.1 -1.3  2.0  3.3
6  1.9  1.3 -1.6 -2.1 -2.3  0.0  1.3
7 -1.1 -1.7  0.4 -2.1  1.7 -1.0  0.3
8  0.9 -1.7  1.4 -0.1  1.7 -2.0  0.3
9 -1.1  0.3 -2.6  1.9 -3.3  0.0 -1.7

In [18]:
def Chebyshev_inequality(index , row_value, cov_matrix_invs):
    
    #(X-µ) transpose
    row_value_transpose = np.transpose(np.asmatrix(row_value))
    print ("trns", row_value_transpose)
    x_mlp_cov = row_value* cov_matrix_invs
    print ("x_mlp_cov", x_mlp_cov)
    
    x_mlp_cov_mlp_x_tsp = np.sqrt(x_mlp_cov * row_value_transpose)
    print (x_mlp_cov_mlp_x_tsp)
    if (x_mlp_cov_mlp_x_tsp > 8.366600265340756):
        return False
    else: 
        return True




In [235]:
Chebyshev_inequality(1,x_sub_mean_all.iloc[6].values, cov_matrix_invs)

trns [[ 1.9]
 [ 1.3]
 [-1.6]
 [-2.1]
 [-2.3]
 [ 0. ]
 [ 1.3]]
x_mlp_cov [[ 1.14656433  0.29413859 -0.64752882  0.22287991 -0.37115469 -0.4505516
   1.57204777]]
[[2.45482557]]


True

In [127]:
x_sub_mean_all.iloc[0].values

array([-1.28571429, -1.28571429,  0.85714286, -1.28571429,  0.14285714])

In [10]:
matrix2

matrix([[3, 2, 4, 2, 4],
        [5, 2, 6, 1, 4],
        [3, 4, 1, 3, 2],
        [7, 2, 1, 4, 1],
        [4, 5, 4, 5, 4],
        [2, 3, 4, 5, 7],
        [6, 5, 2, 3, 5]])

In [11]:
co_v_M = np.cov(matrix2,rowvar=0)

In [134]:
co_v_M_I = np.linalg.inv(co_v_M)

In [36]:
co_v_M_I

NameError: name 'co_v_M_I' is not defined

In [137]:
mean_of_matrix2 = np.mean(matrix2, axis=0)

In [138]:
mean_of_matrix2

matrix([[4.28571429, 3.28571429, 3.14285714, 3.28571429, 3.85714286]])

In [202]:
#(X-µ)
x_sub_mean = np.subtract(matrix2[5], mean_of_matrix2)

In [203]:
x_sub_mean

matrix([[-2.28571429, -0.28571429,  0.85714286,  1.71428571,  3.14285714]])

In [204]:
#(X-µ) transpose
x_mean_transpose = numpy.transpose(x_sub_mean)
x_mean_transpose

matrix([[-2.28571429],
        [-0.28571429],
        [ 0.85714286],
        [ 1.71428571],
        [ 3.14285714]])

In [35]:
co_v_M_I

NameError: name 'co_v_M_I' is not defined

In [34]:
Final111 = x_sub_mean* co_v_M_I

NameError: name 'co_v_M_I' is not defined

In [207]:
Final111

matrix([[-0.24237647, -0.91451843, -0.3870999 ,  0.70512957,  0.9471325 ]])

In [208]:
final12 = Final111 * x_mean_transpose;

In [209]:
final12

matrix([[4.66899012]])

In [210]:
np.sqrt(final12)

matrix([[2.16078461]])

In [219]:
#define T value 
t = 7/0.10

In [220]:
t


70.0

In [221]:
np.sqrt(t)

8.366600265340756